########################################################################################################
#                               MultiAction - INI
########################################################################################################
acme_multiAction:
   resource: "@AcmeBackendBundle/Controller/MultiActionController.php"
   type:     annotation
   prefix:  /
