acme_terminal_omnibus:
    resource: "@AcmeTerminalOmnibusBundle/Resources/config/routing.yml"
    prefix:   /

acme_backend:
    resource: "@AcmeBackendBundle/Resources/config/routing.yml"
    prefix:   /

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#EndroidQrCodeBundle:
#    resource:   "@EndroidQrCodeBundle/Controller/"
#    type:       annotation
#    prefix:     /qrcode